### ISSUE TITLE
Select a keyboard for installer (required for configuring the time, setting a disk encryption password, and potentially for other disk configuration) and live session

### ISSUE THREAD

**Issue by M4rtinK** [rhinstaller/anaconda-webui#2] opened 2023-03-28 14:32 UTC
NOTE: Workstation WG is investigating if the Live environment could provide this functionality. Then the Anaconda Web UI would not have to handle this.

**Comment by jkonecny12** [comment] 2023-03-30 14:25
My proposal for this would be to not deal with keyboard layouts in Anaconda but during installation process just copy what is configured in the Gnome Shell Live env.

We need to find out if that is acceptable solution to SIG.

**Comment by jkonecny12** [comment] 2023-03-30 14:26
Removing frontend because comment https://github.com/rhinstaller/anaconda-webui/issues/2#issuecomment-1490401620 proposing solution done just in background.

**Comment by jkonecny12** [comment] 2023-04-20 14:08
Closing as duplicate of https://github.com/rhinstaller/anaconda-webui/issues/1

**Closed by jkonecny12** 2023-04-20 14:08 UTC
Labels: backend, needs clarification
